# Generated by Django 4.2.5 on 2023-09-21 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_article_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlesection',
            name='is_main',
            field=models.BooleanField(default=False, verbose_name='Основной раздел'),
        ),
    ]
